version: '3'
services:
  data_base:
    container_name: data_base
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./CADASTRO_PRODUTOS.csv:/docker-entrypoint-initdb.d/CADASTRO_PRODUTOS.csv
    ports:
      - 5432:5432
    networks:
      - data_base

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - 5050:5050
    networks:
      - data_base    
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    depends_on:
      - data_base  # Garante que o banco de dados esteja pronto antes do app
    networks:
      - data_base
    ports:
      - 8000:8000  # Exemplo de porta para expor seu app (ajuste conforme necessário)
      
networks:
  data_base:
    driver: bridge

volumes:
  postgresql_bin:
  pgadmin_root_prefs:
  pgadmin_working_dir: